# https://www.youtube.com/watch?v=RcxvrhQKv8I

### Get all characters
GET https://rickandmortyapi.com/api/character

### Search for character
https://rickandmortyapi.com/api/character/?name=Rick&page=1
